"""Reference values for the filtering diagnostic used in paper 2 (Table III).

For a smooth signal plus white noise of standard deviation sigma, the second
difference

    d2[i] = y[i] - 2 y[i+1] + y[i+2]

has variance 6 sigma^2 and lag-1 autocorrelation exactly -4/6 = -0.667. Any
pre-processing changes both numbers, so ac1(d2) tells you whether sigma_hat =
std(d2)/sqrt(6) is an instrument noise floor at all.

The reference record is a synthetic temperature rise shaped like one B0005
discharge: 197 samples over 3690 s at a constant 2 A, generated by the lumped
model with the median coefficients of the final fit (nasa_final_fits.csv,
h = 24.81 W/m2K). Each noisy case is repeated over 200 seeds and the median is
reported. A last row adds a 19-sample rest after the load, to show what the
current switch-off alone does to the statistic.

No measurement data is needed. Output: results/p2_noise_reference.log
"""
import numpy as np

# ---- synthetic record, B0005-like ------------------------------------------ #
L, V_CELL, RHO_CP = 0.018, np.pi * 0.009**2 * 0.065, 2500.0 * 1100.0   # (b)
H = 24.81                                   # W/m2K, profile-likelihood value
R0, C1, C2 = 0.15299, -1.352, 2.192         # medians of the final fit
N, T_END, I_LOAD, T_AMB = 197, 3690.0, 2.0, 24.0
N_REST = 19                                 # rest samples in the last row
TAU = RHO_CP * L / (2.0 * H)


def record(n_load):
    """Lumped-model surface temperature; current is off after n_load samples."""
    t = np.linspace(0.0, T_END, N)
    I = np.where(np.arange(N) < n_load, I_LOAD, 0.0)
    q_int = np.concatenate([[0.0], np.cumsum(I[:-1] * np.diff(t))])
    x = q_int / q_int[-1]
    q = I**2 * R0 * (1.0 + C1 * x + C2 * x**2) / V_CELL
    theta = np.zeros(N)
    for i in range(N - 1):
        E = np.exp(-(t[i + 1] - t[i]) / TAU)
        theta[i + 1] = theta[i] * E + (q[i] / RHO_CP) * TAU * (1.0 - E)
    return T_AMB + theta


def diagnose(y):
    """-> (sigma_hat, lag-1 autocorrelation of the second difference)."""
    d2 = y[2:] - 2.0 * y[1:-1] + y[:-2]
    return float(np.std(d2) / np.sqrt(6.0)), float(np.sum(d2[:-1] * d2[1:]) / np.sum(d2**2))


def boxcar(y, n):
    return np.convolve(y, np.ones(n) / n, mode="valid")


def interpolated_noise(rng, sigma):
    """White noise drawn on every other sample and linearly interpolated."""
    coarse = rng.normal(0.0, sigma, (N + 1) // 2)
    return np.interp(np.arange(N), np.arange(0, N, 2)[: coarse.size], coarse)


signal = record(N)
with_rest = record(N - N_REST)
SEEDS = range(200)
SIGMA_FILT = 0.10       # K, noise level for the pre-processed cases

cases = []
for s in (0.10, 0.02, 0.005):
    r = [diagnose(signal + np.random.default_rng(k).normal(0.0, s, N)) for k in SEEDS]
    cases.append((f"white noise, sigma = {s:g} K", s, r))
for n in (3, 5):
    r = [diagnose(boxcar(signal + np.random.default_rng(k).normal(0.0, SIGMA_FILT, N), n))
         for k in SEEDS]
    cases.append((f"{n}-point boxcar, sigma = {SIGMA_FILT:g} K", SIGMA_FILT, r))
r = [diagnose(signal + interpolated_noise(np.random.default_rng(k), SIGMA_FILT)) for k in SEEDS]
cases.append((f"linear interpolation, sigma = {SIGMA_FILT:g} K", SIGMA_FILT, r))
cases.append(("noiseless signal", None, [diagnose(signal)]))
cases.append((f"noiseless, with {N_REST}-sample rest", None, [diagnose(with_rest)]))

print("=" * 86)
print("FILTERING DIAGNOSTIC -- reference values on a synthetic B0005-like rise")
print("=" * 86)
print(f"  {N} samples over {T_END:.0f} s at {I_LOAD:g} A, "
      f"rise {signal.max() - signal[0]:.2f} K, tau {TAU:.0f} s")
print(f"  white-noise theory: ac1(d2) = -4/6 = {-4/6:.4f}, sigma_hat = sigma")
print(f"  noisy cases: median over {len(SEEDS)} seeds\n")
print(f"  {'series':40s} {'ac1(d2)':>9s} {'sigma_hat (K)':>14s} {'true/est':>9s}")
for label, s, r in cases:
    sig = np.median([a for a, _ in r])
    ac = np.median([b for _, b in r])
    ratio = f"{s / sig:9.2f}" if s else f"{'--':>9s}"
    print(f"  {label:40s} {ac:+9.3f} {sig:14.5f} {ratio}")
print()
print("  Reading: near -0.67 the estimate is an instrument floor; near -0.5 the")
print("  series was smoothed; near 0 it was interpolated, or a current step")
print("  dominates; above 0 the second difference is smooth signal curvature and")
print("  sigma_hat says nothing about instrument noise.")
